# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    toto:
                        password: 1234
                        roles: 'ROLE-USER'
                    admin:
                        password: '$2y$12$T39md6n5dBNgFh7c/yWPueI0aPg6Gyh1Yk.GMPyMKZcYhS63LtqbG'
                        roles: 'ROLE_ADMIN'

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            form_login:
                login_path: app_login
                check_path: app_login

            logout:
                path:   /logout
                target: app_login
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN}
